kind: Pod
apiVersion: v1
metadata:
  name: tomvin-app
  labels:
    app: tomvin-app
spec:
  containers:
  - name: tomvin-app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=Hello World! This is a tomvin Kubernetes with kind App"
---
kind: Service
apiVersion: v1
metadata:
  name: tomvin-service
spec:
  selector:
    app: tomvin-app
  ports:
  # Default port used by the image
  - port: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tomvin-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/tomvin"
        backend:
          service:
            name: tomvin-service
            port:
              number: 5678
---